version: "3.5"
services:
  homepage:
    image: nginx:1.23.1-alpine
    container_name: homepage
    ports:
      - "80:80"
    volumes:
      - ./services/homepage:/usr/share/nginx/html
    restart: "unless-stopped"

  jellyfin:
    image: jellyfin/jellyfin:10.8.1
    container_name: jellyfin
    user: ${MY_PUID}:${MY_PGID}
    ports:
      - "8096:8096"
    volumes:
      - ./services/jellyfin/config:/config
      - ./services/jellyfin/cache:/cache
      - ${TV_DIR}:/media/tv
      - ${MOVIES_DIR}:/media/movies
    restart: "unless-stopped"
#    networks:
#      lan:
#        ipv4_address: 192.168.1.100
    # ip statica para facilitar descubrimiento

  sonarr:
    image: lscr.io/linuxserver/sonarr:amd64-version-3.0.8.1507
    container_name: sonarr
    environment:
      - PUID=${MY_PUID}
      - PGID=${MY_PGID}
      - TZ=${TZ}
    volumes:
      - ./services/sonarr/config:/config
      - ${TV_DIR}:/tv #optional
      - ${DOWNLOADS_DIR}:/downloads #optional
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8989:8989"
    restart: "unless-stopped"
    links:
      - "jackett"
      - "qbittorrent"

  radarr:
    image: lscr.io/linuxserver/radarr:4.1.0.6175-ls145
    container_name: radarr
    environment:
      - PUID=${MY_PUID}
      - PGID=${MY_PGID}
      - TZ=${TZ}
    volumes:
      - ./services/radarr/config:/config
      - ${MOVIES_DIR}:/movies
      - ${DOWNLOADS_DIR}:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    restart: unless-stopped
    links:
      - "jackett"
      - "qbittorrent"


  bazarr:
    image: lscr.io/linuxserver/bazarr:1.1.0
    container_name: bazarr
    environment:
      - PUID=${MY_PUID}
      - PGID=${MY_PGID}
      - TZ=${TZ}
    volumes:
      - ./services/bazarr/config:/config
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6767:6767
    restart: unless-stopped


  # https://hub.docker.com/r/linuxserver/jackett/
  jackett:
    image: lscr.io/linuxserver/jackett:version-v0.20.1326
    container_name: jackett
    environment:
      - PUID=${MY_PUID}
      - PGID=${MY_PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
#      - RUN_OPTS=<run options here> #optional
    volumes:
      - ./services/jackett/config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9117:9117
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${MY_PUID}
      - PGID=${MY_PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ./services/qbittorrent/config:/config
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  filebrowser:
      image: filebrowser/filebrowser:v2
      container_name: filebrowser
      volumes:
          - ${MOVIES_DIR}:/srv/movies
          - ${TV_DIR}:/srv/series
      ports:
          - '8085:80'
      restart: unless-stopped
